// Code generated by mockery v2.53.6. DO NOT EDIT.

package handlers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "shb/internal/models"

	oauth2 "golang.org/x/oauth2"
)

// MockOAuthProvider is an autogenerated mock type for the OAuthProvider type
type MockOAuthProvider struct {
	mock.Mock
}

type MockOAuthProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthProvider) EXPECT() *MockOAuthProvider_Expecter {
	return &MockOAuthProvider_Expecter{mock: &_m.Mock}
}

// CallbackPath provides a mock function with no fields
func (_m *MockOAuthProvider) CallbackPath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CallbackPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOAuthProvider_CallbackPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallbackPath'
type MockOAuthProvider_CallbackPath_Call struct {
	*mock.Call
}

// CallbackPath is a helper method to define mock.On call
func (_e *MockOAuthProvider_Expecter) CallbackPath() *MockOAuthProvider_CallbackPath_Call {
	return &MockOAuthProvider_CallbackPath_Call{Call: _e.mock.On("CallbackPath")}
}

func (_c *MockOAuthProvider_CallbackPath_Call) Run(run func()) *MockOAuthProvider_CallbackPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOAuthProvider_CallbackPath_Call) Return(_a0 string) *MockOAuthProvider_CallbackPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOAuthProvider_CallbackPath_Call) RunAndReturn(run func() string) *MockOAuthProvider_CallbackPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, tok
func (_m *MockOAuthProvider) GetUser(ctx context.Context, tok *oauth2.Token) (models.OAuthUserInfo, error) {
	ret := _m.Called(ctx, tok)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 models.OAuthUserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *oauth2.Token) (models.OAuthUserInfo, error)); ok {
		return rf(ctx, tok)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *oauth2.Token) models.OAuthUserInfo); ok {
		r0 = rf(ctx, tok)
	} else {
		r0 = ret.Get(0).(models.OAuthUserInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *oauth2.Token) error); ok {
		r1 = rf(ctx, tok)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthProvider_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockOAuthProvider_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - tok *oauth2.Token
func (_e *MockOAuthProvider_Expecter) GetUser(ctx interface{}, tok interface{}) *MockOAuthProvider_GetUser_Call {
	return &MockOAuthProvider_GetUser_Call{Call: _e.mock.On("GetUser", ctx, tok)}
}

func (_c *MockOAuthProvider_GetUser_Call) Run(run func(ctx context.Context, tok *oauth2.Token)) *MockOAuthProvider_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*oauth2.Token))
	})
	return _c
}

func (_c *MockOAuthProvider_GetUser_Call) Return(_a0 models.OAuthUserInfo, _a1 error) *MockOAuthProvider_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthProvider_GetUser_Call) RunAndReturn(run func(context.Context, *oauth2.Token) (models.OAuthUserInfo, error)) *MockOAuthProvider_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// OAuth2Config provides a mock function with no fields
func (_m *MockOAuthProvider) OAuth2Config() *oauth2.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OAuth2Config")
	}

	var r0 *oauth2.Config
	if rf, ok := ret.Get(0).(func() *oauth2.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Config)
		}
	}

	return r0
}

// MockOAuthProvider_OAuth2Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OAuth2Config'
type MockOAuthProvider_OAuth2Config_Call struct {
	*mock.Call
}

// OAuth2Config is a helper method to define mock.On call
func (_e *MockOAuthProvider_Expecter) OAuth2Config() *MockOAuthProvider_OAuth2Config_Call {
	return &MockOAuthProvider_OAuth2Config_Call{Call: _e.mock.On("OAuth2Config")}
}

func (_c *MockOAuthProvider_OAuth2Config_Call) Run(run func()) *MockOAuthProvider_OAuth2Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOAuthProvider_OAuth2Config_Call) Return(_a0 *oauth2.Config) *MockOAuthProvider_OAuth2Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOAuthProvider_OAuth2Config_Call) RunAndReturn(run func() *oauth2.Config) *MockOAuthProvider_OAuth2Config_Call {
	_c.Call.Return(run)
	return _c
}

// ProviderName provides a mock function with no fields
func (_m *MockOAuthProvider) ProviderName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProviderName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOAuthProvider_ProviderName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProviderName'
type MockOAuthProvider_ProviderName_Call struct {
	*mock.Call
}

// ProviderName is a helper method to define mock.On call
func (_e *MockOAuthProvider_Expecter) ProviderName() *MockOAuthProvider_ProviderName_Call {
	return &MockOAuthProvider_ProviderName_Call{Call: _e.mock.On("ProviderName")}
}

func (_c *MockOAuthProvider_ProviderName_Call) Run(run func()) *MockOAuthProvider_ProviderName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOAuthProvider_ProviderName_Call) Return(_a0 string) *MockOAuthProvider_ProviderName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOAuthProvider_ProviderName_Call) RunAndReturn(run func() string) *MockOAuthProvider_ProviderName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOAuthProvider creates a new instance of MockOAuthProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthProvider {
	mock := &MockOAuthProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
