// Code generated by mockery v2.53.6. DO NOT EDIT.

package email

import mock "github.com/stretchr/testify/mock"

// MockISender is an autogenerated mock type for the ISender type
type MockISender struct {
	mock.Mock
}

type MockISender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISender) EXPECT() *MockISender_Expecter {
	return &MockISender_Expecter{mock: &_m.Mock}
}

// SendOTP provides a mock function with given fields: receiver, code
func (_m *MockISender) SendOTP(receiver string, code string) error {
	ret := _m.Called(receiver, code)

	if len(ret) == 0 {
		panic("no return value specified for SendOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(receiver, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISender_SendOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOTP'
type MockISender_SendOTP_Call struct {
	*mock.Call
}

// SendOTP is a helper method to define mock.On call
//   - receiver string
//   - code string
func (_e *MockISender_Expecter) SendOTP(receiver interface{}, code interface{}) *MockISender_SendOTP_Call {
	return &MockISender_SendOTP_Call{Call: _e.mock.On("SendOTP", receiver, code)}
}

func (_c *MockISender_SendOTP_Call) Run(run func(receiver string, code string)) *MockISender_SendOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockISender_SendOTP_Call) Return(_a0 error) *MockISender_SendOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISender_SendOTP_Call) RunAndReturn(run func(string, string) error) *MockISender_SendOTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockISender creates a new instance of MockISender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISender {
	mock := &MockISender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
