// Code generated by mockery v2.53.5. DO NOT EDIT.

package fs

import (
	context "context"
	fs "shb/pkg/external/fs"

	mock "github.com/stretchr/testify/mock"
)

// MockFileWriter is an autogenerated mock type for the FileWriter type
type MockFileWriter struct {
	mock.Mock
}

type MockFileWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileWriter) EXPECT() *MockFileWriter_Expecter {
	return &MockFileWriter_Expecter{mock: &_m.Mock}
}

// WriteFile provides a mock function with given fields: ctx, path, data
func (_m *MockFileWriter) WriteFile(ctx context.Context, path string, data *fs.FileData) (*fs.WriteResult, error) {
	ret := _m.Called(ctx, path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 *fs.WriteResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *fs.FileData) (*fs.WriteResult, error)); ok {
		return rf(ctx, path, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *fs.FileData) *fs.WriteResult); ok {
		r0 = rf(ctx, path, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fs.WriteResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *fs.FileData) error); ok {
		r1 = rf(ctx, path, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileWriter_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockFileWriter_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - data *fs.FileData
func (_e *MockFileWriter_Expecter) WriteFile(ctx interface{}, path interface{}, data interface{}) *MockFileWriter_WriteFile_Call {
	return &MockFileWriter_WriteFile_Call{Call: _e.mock.On("WriteFile", ctx, path, data)}
}

func (_c *MockFileWriter_WriteFile_Call) Run(run func(ctx context.Context, path string, data *fs.FileData)) *MockFileWriter_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*fs.FileData))
	})
	return _c
}

func (_c *MockFileWriter_WriteFile_Call) Return(_a0 *fs.WriteResult, _a1 error) *MockFileWriter_WriteFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileWriter_WriteFile_Call) RunAndReturn(run func(context.Context, string, *fs.FileData) (*fs.WriteResult, error)) *MockFileWriter_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileWriter creates a new instance of MockFileWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileWriter {
	mock := &MockFileWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
