// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Siyovush Hamidov and The Hadaf Contributors

// Code generated by mockery v2.53.6. DO NOT EDIT.

package fs

import (
	context "context"
	fs "shb/pkg/external/fs"

	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// ReadFile provides a mock function with given fields: ctx, path
func (_m *MockStorage) ReadFile(ctx context.Context, path string) (*fs.FileData, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 *fs.FileData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*fs.FileData, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *fs.FileData); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fs.FileData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockStorage_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockStorage_Expecter) ReadFile(ctx interface{}, path interface{}) *MockStorage_ReadFile_Call {
	return &MockStorage_ReadFile_Call{Call: _e.mock.On("ReadFile", ctx, path)}
}

func (_c *MockStorage_ReadFile_Call) Run(run func(ctx context.Context, path string)) *MockStorage_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_ReadFile_Call) Return(_a0 *fs.FileData, _a1 error) *MockStorage_ReadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ReadFile_Call) RunAndReturn(run func(context.Context, string) (*fs.FileData, error)) *MockStorage_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function with given fields: ctx, path, data
func (_m *MockStorage) WriteFile(ctx context.Context, path string, data *fs.FileData) (*fs.WriteResult, error) {
	ret := _m.Called(ctx, path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 *fs.WriteResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *fs.FileData) (*fs.WriteResult, error)); ok {
		return rf(ctx, path, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *fs.FileData) *fs.WriteResult); ok {
		r0 = rf(ctx, path, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fs.WriteResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *fs.FileData) error); ok {
		r1 = rf(ctx, path, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockStorage_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - data *fs.FileData
func (_e *MockStorage_Expecter) WriteFile(ctx interface{}, path interface{}, data interface{}) *MockStorage_WriteFile_Call {
	return &MockStorage_WriteFile_Call{Call: _e.mock.On("WriteFile", ctx, path, data)}
}

func (_c *MockStorage_WriteFile_Call) Run(run func(ctx context.Context, path string, data *fs.FileData)) *MockStorage_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*fs.FileData))
	})
	return _c
}

func (_c *MockStorage_WriteFile_Call) Return(_a0 *fs.WriteResult, _a1 error) *MockStorage_WriteFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_WriteFile_Call) RunAndReturn(run func(context.Context, string, *fs.FileData) (*fs.WriteResult, error)) *MockStorage_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
