// Code generated by mockery v2.53.6. DO NOT EDIT.

package rateLimiter

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIRateLimiter is an autogenerated mock type for the IRateLimiter type
type MockIRateLimiter struct {
	mock.Mock
}

type MockIRateLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRateLimiter) EXPECT() *MockIRateLimiter_Expecter {
	return &MockIRateLimiter_Expecter{mock: &_m.Mock}
}

// Allow provides a mock function with given fields: ctx, key, limit, ttlMinutes
func (_m *MockIRateLimiter) Allow(ctx context.Context, key string, limit int, ttlMinutes int) (bool, error) {
	ret := _m.Called(ctx, key, limit, ttlMinutes)

	if len(ret) == 0 {
		panic("no return value specified for Allow")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (bool, error)); ok {
		return rf(ctx, key, limit, ttlMinutes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) bool); ok {
		r0 = rf(ctx, key, limit, ttlMinutes)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, key, limit, ttlMinutes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRateLimiter_Allow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allow'
type MockIRateLimiter_Allow_Call struct {
	*mock.Call
}

// Allow is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - limit int
//   - ttlMinutes int
func (_e *MockIRateLimiter_Expecter) Allow(ctx interface{}, key interface{}, limit interface{}, ttlMinutes interface{}) *MockIRateLimiter_Allow_Call {
	return &MockIRateLimiter_Allow_Call{Call: _e.mock.On("Allow", ctx, key, limit, ttlMinutes)}
}

func (_c *MockIRateLimiter_Allow_Call) Run(run func(ctx context.Context, key string, limit int, ttlMinutes int)) *MockIRateLimiter_Allow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockIRateLimiter_Allow_Call) Return(_a0 bool, _a1 error) *MockIRateLimiter_Allow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRateLimiter_Allow_Call) RunAndReturn(run func(context.Context, string, int, int) (bool, error)) *MockIRateLimiter_Allow_Call {
	_c.Call.Return(run)
	return _c
}

// ResetAttempts provides a mock function with given fields: ctx, key
func (_m *MockIRateLimiter) ResetAttempts(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for ResetAttempts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRateLimiter_ResetAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetAttempts'
type MockIRateLimiter_ResetAttempts_Call struct {
	*mock.Call
}

// ResetAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockIRateLimiter_Expecter) ResetAttempts(ctx interface{}, key interface{}) *MockIRateLimiter_ResetAttempts_Call {
	return &MockIRateLimiter_ResetAttempts_Call{Call: _e.mock.On("ResetAttempts", ctx, key)}
}

func (_c *MockIRateLimiter_ResetAttempts_Call) Run(run func(ctx context.Context, key string)) *MockIRateLimiter_ResetAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIRateLimiter_ResetAttempts_Call) Return(_a0 error) *MockIRateLimiter_ResetAttempts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRateLimiter_ResetAttempts_Call) RunAndReturn(run func(context.Context, string) error) *MockIRateLimiter_ResetAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRateLimiter creates a new instance of MockIRateLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRateLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRateLimiter {
	mock := &MockIRateLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
