// Code generated by mockery v2.53.6. DO NOT EDIT.

package tokens

import (
	context "context"
	models "shb/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockITokenIssuer is an autogenerated mock type for the ITokenIssuer type
type MockITokenIssuer struct {
	mock.Mock
}

type MockITokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITokenIssuer) EXPECT() *MockITokenIssuer_Expecter {
	return &MockITokenIssuer_Expecter{mock: &_m.Mock}
}

// IssueTokens provides a mock function with given fields: ctx, id, role, isApproved
func (_m *MockITokenIssuer) IssueTokens(ctx context.Context, id int, role string, isApproved bool) (string, string, error) {
	ret := _m.Called(ctx, id, role, isApproved)

	if len(ret) == 0 {
		panic("no return value specified for IssueTokens")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, bool) (string, string, error)); ok {
		return rf(ctx, id, role, isApproved)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, bool) string); ok {
		r0 = rf(ctx, id, role, isApproved)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, bool) string); ok {
		r1 = rf(ctx, id, role, isApproved)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, string, bool) error); ok {
		r2 = rf(ctx, id, role, isApproved)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockITokenIssuer_IssueTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueTokens'
type MockITokenIssuer_IssueTokens_Call struct {
	*mock.Call
}

// IssueTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - role string
//   - isApproved bool
func (_e *MockITokenIssuer_Expecter) IssueTokens(ctx interface{}, id interface{}, role interface{}, isApproved interface{}) *MockITokenIssuer_IssueTokens_Call {
	return &MockITokenIssuer_IssueTokens_Call{Call: _e.mock.On("IssueTokens", ctx, id, role, isApproved)}
}

func (_c *MockITokenIssuer_IssueTokens_Call) Run(run func(ctx context.Context, id int, role string, isApproved bool)) *MockITokenIssuer_IssueTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockITokenIssuer_IssueTokens_Call) Return(_a0 string, _a1 string, _a2 error) *MockITokenIssuer_IssueTokens_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockITokenIssuer_IssueTokens_Call) RunAndReturn(run func(context.Context, int, string, bool) (string, string, error)) *MockITokenIssuer_IssueTokens_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function with given fields: ctx, token
func (_m *MockITokenIssuer) VerifyToken(ctx context.Context, token string) (*models.CustomClaims, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 *models.CustomClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.CustomClaims, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.CustomClaims); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CustomClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITokenIssuer_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockITokenIssuer_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockITokenIssuer_Expecter) VerifyToken(ctx interface{}, token interface{}) *MockITokenIssuer_VerifyToken_Call {
	return &MockITokenIssuer_VerifyToken_Call{Call: _e.mock.On("VerifyToken", ctx, token)}
}

func (_c *MockITokenIssuer_VerifyToken_Call) Run(run func(ctx context.Context, token string)) *MockITokenIssuer_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockITokenIssuer_VerifyToken_Call) Return(_a0 *models.CustomClaims, _a1 error) *MockITokenIssuer_VerifyToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITokenIssuer_VerifyToken_Call) RunAndReturn(run func(context.Context, string) (*models.CustomClaims, error)) *MockITokenIssuer_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockITokenIssuer creates a new instance of MockITokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITokenIssuer {
	mock := &MockITokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
