// Code generated by mockery v2.53.5. DO NOT EDIT.

package tokens

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockITokenIssuer is an autogenerated mock type for the ITokenIssuer type
type MockITokenIssuer struct {
	mock.Mock
}

type MockITokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITokenIssuer) EXPECT() *MockITokenIssuer_Expecter {
	return &MockITokenIssuer_Expecter{mock: &_m.Mock}
}

// IssueTokens provides a mock function with given fields: ctx, id
func (_m *MockITokenIssuer) IssueTokens(ctx context.Context, id int) (string, string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IssueTokens")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (string, string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) string); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockITokenIssuer_IssueTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueTokens'
type MockITokenIssuer_IssueTokens_Call struct {
	*mock.Call
}

// IssueTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockITokenIssuer_Expecter) IssueTokens(ctx interface{}, id interface{}) *MockITokenIssuer_IssueTokens_Call {
	return &MockITokenIssuer_IssueTokens_Call{Call: _e.mock.On("IssueTokens", ctx, id)}
}

func (_c *MockITokenIssuer_IssueTokens_Call) Run(run func(ctx context.Context, id int)) *MockITokenIssuer_IssueTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockITokenIssuer_IssueTokens_Call) Return(_a0 string, _a1 string, _a2 error) *MockITokenIssuer_IssueTokens_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockITokenIssuer_IssueTokens_Call) RunAndReturn(run func(context.Context, int) (string, string, error)) *MockITokenIssuer_IssueTokens_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockITokenIssuer creates a new instance of MockITokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITokenIssuer {
	mock := &MockITokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
