server:
  name: "my-app"
  host: "localhost"
  port: "8000"
  writeTimeout: 30
  readTimeout: 30

logger:
  logPath: ""
  level: "info"
  includeCaller: true

service:
  security:
    sendOTPAttempts: 3
    sendOTPBlockTime: 300
    otpLength: 6
    otpMaxAttempts: 3
    maxLoginAttempts: 5
    otpDuration: "5m"

sms: {}