// Code generated by mockery v2.53.6. DO NOT EDIT.

package sms

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	smsProvider "shb/pkg/external/sms/smsProvider"
)

// MockISmsAdapter is an autogenerated mock type for the ISmsAdapter type
type MockISmsAdapter struct {
	mock.Mock
}

type MockISmsAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISmsAdapter) EXPECT() *MockISmsAdapter_Expecter {
	return &MockISmsAdapter_Expecter{mock: &_m.Mock}
}

// CheckBalance provides a mock function with given fields: ctx
func (_m *MockISmsAdapter) CheckBalance(ctx context.Context) (*smsProvider.BalanceResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckBalance")
	}

	var r0 *smsProvider.BalanceResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*smsProvider.BalanceResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *smsProvider.BalanceResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*smsProvider.BalanceResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockISmsAdapter_CheckBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckBalance'
type MockISmsAdapter_CheckBalance_Call struct {
	*mock.Call
}

// CheckBalance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockISmsAdapter_Expecter) CheckBalance(ctx interface{}) *MockISmsAdapter_CheckBalance_Call {
	return &MockISmsAdapter_CheckBalance_Call{Call: _e.mock.On("CheckBalance", ctx)}
}

func (_c *MockISmsAdapter_CheckBalance_Call) Run(run func(ctx context.Context)) *MockISmsAdapter_CheckBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockISmsAdapter_CheckBalance_Call) Return(_a0 *smsProvider.BalanceResult, _a1 error) *MockISmsAdapter_CheckBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockISmsAdapter_CheckBalance_Call) RunAndReturn(run func(context.Context) (*smsProvider.BalanceResult, error)) *MockISmsAdapter_CheckBalance_Call {
	_c.Call.Return(run)
	return _c
}

// SendSms provides a mock function with given fields: ctx, phone, message, txnID
func (_m *MockISmsAdapter) SendSms(ctx context.Context, phone string, message string, txnID string) error {
	ret := _m.Called(ctx, phone, message, txnID)

	if len(ret) == 0 {
		panic("no return value specified for SendSms")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, phone, message, txnID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISmsAdapter_SendSms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSms'
type MockISmsAdapter_SendSms_Call struct {
	*mock.Call
}

// SendSms is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
//   - message string
//   - txnID string
func (_e *MockISmsAdapter_Expecter) SendSms(ctx interface{}, phone interface{}, message interface{}, txnID interface{}) *MockISmsAdapter_SendSms_Call {
	return &MockISmsAdapter_SendSms_Call{Call: _e.mock.On("SendSms", ctx, phone, message, txnID)}
}

func (_c *MockISmsAdapter_SendSms_Call) Run(run func(ctx context.Context, phone string, message string, txnID string)) *MockISmsAdapter_SendSms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockISmsAdapter_SendSms_Call) Return(_a0 error) *MockISmsAdapter_SendSms_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISmsAdapter_SendSms_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockISmsAdapter_SendSms_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockISmsAdapter creates a new instance of MockISmsAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISmsAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISmsAdapter {
	mock := &MockISmsAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
