// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"
	models "shb/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *MockIRepository) CreateUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockIRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockIRepository_Expecter) CreateUser(ctx interface{}, user interface{}) *MockIRepository_CreateUser_Call {
	return &MockIRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockIRepository_CreateUser_Call) Run(run func(ctx context.Context, user *models.User)) *MockIRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockIRepository_CreateUser_Call) Return(_a0 error) *MockIRepository_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepository_CreateUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *MockIRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetOTP provides a mock function with given fields: ctx, phone
func (_m *MockIRepository) GetOTP(ctx context.Context, phone string) (*models.OTP, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for GetOTP")
	}

	var r0 *models.OTP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.OTP, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.OTP); ok {
		r0 = rf(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OTP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_GetOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOTP'
type MockIRepository_GetOTP_Call struct {
	*mock.Call
}

// GetOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockIRepository_Expecter) GetOTP(ctx interface{}, phone interface{}) *MockIRepository_GetOTP_Call {
	return &MockIRepository_GetOTP_Call{Call: _e.mock.On("GetOTP", ctx, phone)}
}

func (_c *MockIRepository_GetOTP_Call) Run(run func(ctx context.Context, phone string)) *MockIRepository_GetOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIRepository_GetOTP_Call) Return(_a0 *models.OTP, _a1 error) *MockIRepository_GetOTP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_GetOTP_Call) RunAndReturn(run func(context.Context, string) (*models.OTP, error)) *MockIRepository_GetOTP_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByPhone provides a mock function with given fields: ctx, phone
func (_m *MockIRepository) GetUserByPhone(ctx context.Context, phone string) (*models.User, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByPhone")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_GetUserByPhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByPhone'
type MockIRepository_GetUserByPhone_Call struct {
	*mock.Call
}

// GetUserByPhone is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockIRepository_Expecter) GetUserByPhone(ctx interface{}, phone interface{}) *MockIRepository_GetUserByPhone_Call {
	return &MockIRepository_GetUserByPhone_Call{Call: _e.mock.On("GetUserByPhone", ctx, phone)}
}

func (_c *MockIRepository_GetUserByPhone_Call) Run(run func(ctx context.Context, phone string)) *MockIRepository_GetUserByPhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIRepository_GetUserByPhone_Call) Return(_a0 *models.User, _a1 error) *MockIRepository_GetUserByPhone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_GetUserByPhone_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockIRepository_GetUserByPhone_Call {
	_c.Call.Return(run)
	return _c
}

// IncreaseOTPAttempt provides a mock function with given fields: ctx, otpID, phone
func (_m *MockIRepository) IncreaseOTPAttempt(ctx context.Context, otpID int, phone string) error {
	ret := _m.Called(ctx, otpID, phone)

	if len(ret) == 0 {
		panic("no return value specified for IncreaseOTPAttempt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, otpID, phone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRepository_IncreaseOTPAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncreaseOTPAttempt'
type MockIRepository_IncreaseOTPAttempt_Call struct {
	*mock.Call
}

// IncreaseOTPAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - otpID int
//   - phone string
func (_e *MockIRepository_Expecter) IncreaseOTPAttempt(ctx interface{}, otpID interface{}, phone interface{}) *MockIRepository_IncreaseOTPAttempt_Call {
	return &MockIRepository_IncreaseOTPAttempt_Call{Call: _e.mock.On("IncreaseOTPAttempt", ctx, otpID, phone)}
}

func (_c *MockIRepository_IncreaseOTPAttempt_Call) Run(run func(ctx context.Context, otpID int, phone string)) *MockIRepository_IncreaseOTPAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockIRepository_IncreaseOTPAttempt_Call) Return(_a0 error) *MockIRepository_IncreaseOTPAttempt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepository_IncreaseOTPAttempt_Call) RunAndReturn(run func(context.Context, int, string) error) *MockIRepository_IncreaseOTPAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOTPAsVerified provides a mock function with given fields: ctx, otpID
func (_m *MockIRepository) MarkOTPAsVerified(ctx context.Context, otpID int) error {
	ret := _m.Called(ctx, otpID)

	if len(ret) == 0 {
		panic("no return value specified for MarkOTPAsVerified")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, otpID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRepository_MarkOTPAsVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOTPAsVerified'
type MockIRepository_MarkOTPAsVerified_Call struct {
	*mock.Call
}

// MarkOTPAsVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - otpID int
func (_e *MockIRepository_Expecter) MarkOTPAsVerified(ctx interface{}, otpID interface{}) *MockIRepository_MarkOTPAsVerified_Call {
	return &MockIRepository_MarkOTPAsVerified_Call{Call: _e.mock.On("MarkOTPAsVerified", ctx, otpID)}
}

func (_c *MockIRepository_MarkOTPAsVerified_Call) Run(run func(ctx context.Context, otpID int)) *MockIRepository_MarkOTPAsVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIRepository_MarkOTPAsVerified_Call) Return(_a0 error) *MockIRepository_MarkOTPAsVerified_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepository_MarkOTPAsVerified_Call) RunAndReturn(run func(context.Context, int) error) *MockIRepository_MarkOTPAsVerified_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOTP provides a mock function with given fields: ctx, o
func (_m *MockIRepository) SaveOTP(ctx context.Context, o *models.OTP) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for SaveOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.OTP) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRepository_SaveOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOTP'
type MockIRepository_SaveOTP_Call struct {
	*mock.Call
}

// SaveOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - o *models.OTP
func (_e *MockIRepository_Expecter) SaveOTP(ctx interface{}, o interface{}) *MockIRepository_SaveOTP_Call {
	return &MockIRepository_SaveOTP_Call{Call: _e.mock.On("SaveOTP", ctx, o)}
}

func (_c *MockIRepository_SaveOTP_Call) Run(run func(ctx context.Context, o *models.OTP)) *MockIRepository_SaveOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.OTP))
	})
	return _c
}

func (_c *MockIRepository_SaveOTP_Call) Return(_a0 error) *MockIRepository_SaveOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepository_SaveOTP_Call) RunAndReturn(run func(context.Context, *models.OTP) error) *MockIRepository_SaveOTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
