// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"
	filters "shb/internal/repositories/filters"

	mock "github.com/stretchr/testify/mock"

	models "shb/internal/models"
)

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// CreateBooking provides a mock function with given fields: ctx, booking
func (_m *MockIRepository) CreateBooking(ctx context.Context, booking *models.Booking) (int, error) {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Booking) (int, error)); ok {
		return rf(ctx, booking)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Booking) int); ok {
		r0 = rf(ctx, booking)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Booking) error); ok {
		r1 = rf(ctx, booking)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_CreateBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBooking'
type MockIRepository_CreateBooking_Call struct {
	*mock.Call
}

// CreateBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - booking *models.Booking
func (_e *MockIRepository_Expecter) CreateBooking(ctx interface{}, booking interface{}) *MockIRepository_CreateBooking_Call {
	return &MockIRepository_CreateBooking_Call{Call: _e.mock.On("CreateBooking", ctx, booking)}
}

func (_c *MockIRepository_CreateBooking_Call) Run(run func(ctx context.Context, booking *models.Booking)) *MockIRepository_CreateBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Booking))
	})
	return _c
}

func (_c *MockIRepository_CreateBooking_Call) Return(_a0 int, _a1 error) *MockIRepository_CreateBooking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_CreateBooking_Call) RunAndReturn(run func(context.Context, *models.Booking) (int, error)) *MockIRepository_CreateBooking_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInstitution provides a mock function with given fields: ctx, i
func (_m *MockIRepository) CreateInstitution(ctx context.Context, i *models.Institution) (int, error) {
	ret := _m.Called(ctx, i)

	if len(ret) == 0 {
		panic("no return value specified for CreateInstitution")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Institution) (int, error)); ok {
		return rf(ctx, i)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Institution) int); ok {
		r0 = rf(ctx, i)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Institution) error); ok {
		r1 = rf(ctx, i)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_CreateInstitution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInstitution'
type MockIRepository_CreateInstitution_Call struct {
	*mock.Call
}

// CreateInstitution is a helper method to define mock.On call
//   - ctx context.Context
//   - i *models.Institution
func (_e *MockIRepository_Expecter) CreateInstitution(ctx interface{}, i interface{}) *MockIRepository_CreateInstitution_Call {
	return &MockIRepository_CreateInstitution_Call{Call: _e.mock.On("CreateInstitution", ctx, i)}
}

func (_c *MockIRepository_CreateInstitution_Call) Run(run func(ctx context.Context, i *models.Institution)) *MockIRepository_CreateInstitution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Institution))
	})
	return _c
}

func (_c *MockIRepository_CreateInstitution_Call) Return(_a0 int, _a1 error) *MockIRepository_CreateInstitution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_CreateInstitution_Call) RunAndReturn(run func(context.Context, *models.Institution) (int, error)) *MockIRepository_CreateInstitution_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNeed provides a mock function with given fields: ctx, need
func (_m *MockIRepository) CreateNeed(ctx context.Context, need *models.Need) (int, error) {
	ret := _m.Called(ctx, need)

	if len(ret) == 0 {
		panic("no return value specified for CreateNeed")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Need) (int, error)); ok {
		return rf(ctx, need)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Need) int); ok {
		r0 = rf(ctx, need)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Need) error); ok {
		r1 = rf(ctx, need)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_CreateNeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNeed'
type MockIRepository_CreateNeed_Call struct {
	*mock.Call
}

// CreateNeed is a helper method to define mock.On call
//   - ctx context.Context
//   - need *models.Need
func (_e *MockIRepository_Expecter) CreateNeed(ctx interface{}, need interface{}) *MockIRepository_CreateNeed_Call {
	return &MockIRepository_CreateNeed_Call{Call: _e.mock.On("CreateNeed", ctx, need)}
}

func (_c *MockIRepository_CreateNeed_Call) Run(run func(ctx context.Context, need *models.Need)) *MockIRepository_CreateNeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Need))
	})
	return _c
}

func (_c *MockIRepository_CreateNeed_Call) Return(_a0 int, _a1 error) *MockIRepository_CreateNeed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_CreateNeed_Call) RunAndReturn(run func(context.Context, *models.Need) (int, error)) *MockIRepository_CreateNeed_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *MockIRepository) CreateUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockIRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockIRepository_Expecter) CreateUser(ctx interface{}, user interface{}) *MockIRepository_CreateUser_Call {
	return &MockIRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockIRepository_CreateUser_Call) Run(run func(ctx context.Context, user *models.User)) *MockIRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockIRepository_CreateUser_Call) Return(_a0 error) *MockIRepository_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepository_CreateUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *MockIRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNeed provides a mock function with given fields: ctx, id
func (_m *MockIRepository) DeleteNeed(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNeed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRepository_DeleteNeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNeed'
type MockIRepository_DeleteNeed_Call struct {
	*mock.Call
}

// DeleteNeed is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockIRepository_Expecter) DeleteNeed(ctx interface{}, id interface{}) *MockIRepository_DeleteNeed_Call {
	return &MockIRepository_DeleteNeed_Call{Call: _e.mock.On("DeleteNeed", ctx, id)}
}

func (_c *MockIRepository_DeleteNeed_Call) Run(run func(ctx context.Context, id int)) *MockIRepository_DeleteNeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIRepository_DeleteNeed_Call) Return(_a0 error) *MockIRepository_DeleteNeed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepository_DeleteNeed_Call) RunAndReturn(run func(context.Context, int) error) *MockIRepository_DeleteNeed_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllInstitutions provides a mock function with given fields: ctx, filter
func (_m *MockIRepository) GetAllInstitutions(ctx context.Context, filter filters.InstitutionFilter) ([]*models.Institution, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllInstitutions")
	}

	var r0 []*models.Institution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, filters.InstitutionFilter) ([]*models.Institution, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, filters.InstitutionFilter) []*models.Institution); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Institution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, filters.InstitutionFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_GetAllInstitutions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllInstitutions'
type MockIRepository_GetAllInstitutions_Call struct {
	*mock.Call
}

// GetAllInstitutions is a helper method to define mock.On call
//   - ctx context.Context
//   - filter filters.InstitutionFilter
func (_e *MockIRepository_Expecter) GetAllInstitutions(ctx interface{}, filter interface{}) *MockIRepository_GetAllInstitutions_Call {
	return &MockIRepository_GetAllInstitutions_Call{Call: _e.mock.On("GetAllInstitutions", ctx, filter)}
}

func (_c *MockIRepository_GetAllInstitutions_Call) Run(run func(ctx context.Context, filter filters.InstitutionFilter)) *MockIRepository_GetAllInstitutions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(filters.InstitutionFilter))
	})
	return _c
}

func (_c *MockIRepository_GetAllInstitutions_Call) Return(_a0 []*models.Institution, _a1 error) *MockIRepository_GetAllInstitutions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_GetAllInstitutions_Call) RunAndReturn(run func(context.Context, filters.InstitutionFilter) ([]*models.Institution, error)) *MockIRepository_GetAllInstitutions_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingByID provides a mock function with given fields: ctx, id
func (_m *MockIRepository) GetBookingByID(ctx context.Context, id int) (*models.Booking, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingByID")
	}

	var r0 *models.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Booking, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Booking); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_GetBookingByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingByID'
type MockIRepository_GetBookingByID_Call struct {
	*mock.Call
}

// GetBookingByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockIRepository_Expecter) GetBookingByID(ctx interface{}, id interface{}) *MockIRepository_GetBookingByID_Call {
	return &MockIRepository_GetBookingByID_Call{Call: _e.mock.On("GetBookingByID", ctx, id)}
}

func (_c *MockIRepository_GetBookingByID_Call) Run(run func(ctx context.Context, id int)) *MockIRepository_GetBookingByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIRepository_GetBookingByID_Call) Return(_a0 *models.Booking, _a1 error) *MockIRepository_GetBookingByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_GetBookingByID_Call) RunAndReturn(run func(context.Context, int) (*models.Booking, error)) *MockIRepository_GetBookingByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingsByInstitution provides a mock function with given fields: ctx, institutionID
func (_m *MockIRepository) GetBookingsByInstitution(ctx context.Context, institutionID int) ([]*models.Booking, error) {
	ret := _m.Called(ctx, institutionID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsByInstitution")
	}

	var r0 []*models.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*models.Booking, error)); ok {
		return rf(ctx, institutionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.Booking); ok {
		r0 = rf(ctx, institutionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, institutionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_GetBookingsByInstitution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsByInstitution'
type MockIRepository_GetBookingsByInstitution_Call struct {
	*mock.Call
}

// GetBookingsByInstitution is a helper method to define mock.On call
//   - ctx context.Context
//   - institutionID int
func (_e *MockIRepository_Expecter) GetBookingsByInstitution(ctx interface{}, institutionID interface{}) *MockIRepository_GetBookingsByInstitution_Call {
	return &MockIRepository_GetBookingsByInstitution_Call{Call: _e.mock.On("GetBookingsByInstitution", ctx, institutionID)}
}

func (_c *MockIRepository_GetBookingsByInstitution_Call) Run(run func(ctx context.Context, institutionID int)) *MockIRepository_GetBookingsByInstitution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIRepository_GetBookingsByInstitution_Call) Return(_a0 []*models.Booking, _a1 error) *MockIRepository_GetBookingsByInstitution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_GetBookingsByInstitution_Call) RunAndReturn(run func(context.Context, int) ([]*models.Booking, error)) *MockIRepository_GetBookingsByInstitution_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingsByNeed provides a mock function with given fields: ctx, needID
func (_m *MockIRepository) GetBookingsByNeed(ctx context.Context, needID int) ([]*models.Booking, error) {
	ret := _m.Called(ctx, needID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsByNeed")
	}

	var r0 []*models.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*models.Booking, error)); ok {
		return rf(ctx, needID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.Booking); ok {
		r0 = rf(ctx, needID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, needID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_GetBookingsByNeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsByNeed'
type MockIRepository_GetBookingsByNeed_Call struct {
	*mock.Call
}

// GetBookingsByNeed is a helper method to define mock.On call
//   - ctx context.Context
//   - needID int
func (_e *MockIRepository_Expecter) GetBookingsByNeed(ctx interface{}, needID interface{}) *MockIRepository_GetBookingsByNeed_Call {
	return &MockIRepository_GetBookingsByNeed_Call{Call: _e.mock.On("GetBookingsByNeed", ctx, needID)}
}

func (_c *MockIRepository_GetBookingsByNeed_Call) Run(run func(ctx context.Context, needID int)) *MockIRepository_GetBookingsByNeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIRepository_GetBookingsByNeed_Call) Return(_a0 []*models.Booking, _a1 error) *MockIRepository_GetBookingsByNeed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_GetBookingsByNeed_Call) RunAndReturn(run func(context.Context, int) ([]*models.Booking, error)) *MockIRepository_GetBookingsByNeed_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingsByUser provides a mock function with given fields: ctx, userID
func (_m *MockIRepository) GetBookingsByUser(ctx context.Context, userID int) ([]*models.Booking, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsByUser")
	}

	var r0 []*models.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*models.Booking, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.Booking); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_GetBookingsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsByUser'
type MockIRepository_GetBookingsByUser_Call struct {
	*mock.Call
}

// GetBookingsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockIRepository_Expecter) GetBookingsByUser(ctx interface{}, userID interface{}) *MockIRepository_GetBookingsByUser_Call {
	return &MockIRepository_GetBookingsByUser_Call{Call: _e.mock.On("GetBookingsByUser", ctx, userID)}
}

func (_c *MockIRepository_GetBookingsByUser_Call) Run(run func(ctx context.Context, userID int)) *MockIRepository_GetBookingsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIRepository_GetBookingsByUser_Call) Return(_a0 []*models.Booking, _a1 error) *MockIRepository_GetBookingsByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_GetBookingsByUser_Call) RunAndReturn(run func(context.Context, int) ([]*models.Booking, error)) *MockIRepository_GetBookingsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstitutionByID provides a mock function with given fields: ctx, id
func (_m *MockIRepository) GetInstitutionByID(ctx context.Context, id int) (*models.Institution, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetInstitutionByID")
	}

	var r0 *models.Institution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Institution, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Institution); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Institution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_GetInstitutionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstitutionByID'
type MockIRepository_GetInstitutionByID_Call struct {
	*mock.Call
}

// GetInstitutionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockIRepository_Expecter) GetInstitutionByID(ctx interface{}, id interface{}) *MockIRepository_GetInstitutionByID_Call {
	return &MockIRepository_GetInstitutionByID_Call{Call: _e.mock.On("GetInstitutionByID", ctx, id)}
}

func (_c *MockIRepository_GetInstitutionByID_Call) Run(run func(ctx context.Context, id int)) *MockIRepository_GetInstitutionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIRepository_GetInstitutionByID_Call) Return(_a0 *models.Institution, _a1 error) *MockIRepository_GetInstitutionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_GetInstitutionByID_Call) RunAndReturn(run func(context.Context, int) (*models.Institution, error)) *MockIRepository_GetInstitutionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNeedByID provides a mock function with given fields: ctx, id
func (_m *MockIRepository) GetNeedByID(ctx context.Context, id int) (*models.Need, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNeedByID")
	}

	var r0 *models.Need
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Need, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Need); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Need)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_GetNeedByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNeedByID'
type MockIRepository_GetNeedByID_Call struct {
	*mock.Call
}

// GetNeedByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockIRepository_Expecter) GetNeedByID(ctx interface{}, id interface{}) *MockIRepository_GetNeedByID_Call {
	return &MockIRepository_GetNeedByID_Call{Call: _e.mock.On("GetNeedByID", ctx, id)}
}

func (_c *MockIRepository_GetNeedByID_Call) Run(run func(ctx context.Context, id int)) *MockIRepository_GetNeedByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIRepository_GetNeedByID_Call) Return(_a0 *models.Need, _a1 error) *MockIRepository_GetNeedByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_GetNeedByID_Call) RunAndReturn(run func(context.Context, int) (*models.Need, error)) *MockIRepository_GetNeedByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNeedsByInstitution provides a mock function with given fields: ctx, filter, institutionID
func (_m *MockIRepository) GetNeedsByInstitution(ctx context.Context, filter filters.NeedsFilter, institutionID int) ([]*models.Need, error) {
	ret := _m.Called(ctx, filter, institutionID)

	if len(ret) == 0 {
		panic("no return value specified for GetNeedsByInstitution")
	}

	var r0 []*models.Need
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, filters.NeedsFilter, int) ([]*models.Need, error)); ok {
		return rf(ctx, filter, institutionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, filters.NeedsFilter, int) []*models.Need); ok {
		r0 = rf(ctx, filter, institutionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Need)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, filters.NeedsFilter, int) error); ok {
		r1 = rf(ctx, filter, institutionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_GetNeedsByInstitution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNeedsByInstitution'
type MockIRepository_GetNeedsByInstitution_Call struct {
	*mock.Call
}

// GetNeedsByInstitution is a helper method to define mock.On call
//   - ctx context.Context
//   - filter filters.NeedsFilter
//   - institutionID int
func (_e *MockIRepository_Expecter) GetNeedsByInstitution(ctx interface{}, filter interface{}, institutionID interface{}) *MockIRepository_GetNeedsByInstitution_Call {
	return &MockIRepository_GetNeedsByInstitution_Call{Call: _e.mock.On("GetNeedsByInstitution", ctx, filter, institutionID)}
}

func (_c *MockIRepository_GetNeedsByInstitution_Call) Run(run func(ctx context.Context, filter filters.NeedsFilter, institutionID int)) *MockIRepository_GetNeedsByInstitution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(filters.NeedsFilter), args[2].(int))
	})
	return _c
}

func (_c *MockIRepository_GetNeedsByInstitution_Call) Return(_a0 []*models.Need, _a1 error) *MockIRepository_GetNeedsByInstitution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_GetNeedsByInstitution_Call) RunAndReturn(run func(context.Context, filters.NeedsFilter, int) ([]*models.Need, error)) *MockIRepository_GetNeedsByInstitution_Call {
	_c.Call.Return(run)
	return _c
}

// GetOTP provides a mock function with given fields: ctx, phone
func (_m *MockIRepository) GetOTP(ctx context.Context, phone string) (*models.OTP, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for GetOTP")
	}

	var r0 *models.OTP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.OTP, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.OTP); ok {
		r0 = rf(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OTP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_GetOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOTP'
type MockIRepository_GetOTP_Call struct {
	*mock.Call
}

// GetOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockIRepository_Expecter) GetOTP(ctx interface{}, phone interface{}) *MockIRepository_GetOTP_Call {
	return &MockIRepository_GetOTP_Call{Call: _e.mock.On("GetOTP", ctx, phone)}
}

func (_c *MockIRepository_GetOTP_Call) Run(run func(ctx context.Context, phone string)) *MockIRepository_GetOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIRepository_GetOTP_Call) Return(_a0 *models.OTP, _a1 error) *MockIRepository_GetOTP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_GetOTP_Call) RunAndReturn(run func(context.Context, string) (*models.OTP, error)) *MockIRepository_GetOTP_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockIRepository) GetUserByID(ctx context.Context, id int) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockIRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockIRepository_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockIRepository_GetUserByID_Call {
	return &MockIRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockIRepository_GetUserByID_Call) Run(run func(ctx context.Context, id int)) *MockIRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIRepository_GetUserByID_Call) Return(_a0 *models.User, _a1 error) *MockIRepository_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_GetUserByID_Call) RunAndReturn(run func(context.Context, int) (*models.User, error)) *MockIRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByPhone provides a mock function with given fields: ctx, phone
func (_m *MockIRepository) GetUserByPhone(ctx context.Context, phone string) (*models.User, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByPhone")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_GetUserByPhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByPhone'
type MockIRepository_GetUserByPhone_Call struct {
	*mock.Call
}

// GetUserByPhone is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockIRepository_Expecter) GetUserByPhone(ctx interface{}, phone interface{}) *MockIRepository_GetUserByPhone_Call {
	return &MockIRepository_GetUserByPhone_Call{Call: _e.mock.On("GetUserByPhone", ctx, phone)}
}

func (_c *MockIRepository_GetUserByPhone_Call) Run(run func(ctx context.Context, phone string)) *MockIRepository_GetUserByPhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIRepository_GetUserByPhone_Call) Return(_a0 *models.User, _a1 error) *MockIRepository_GetUserByPhone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_GetUserByPhone_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockIRepository_GetUserByPhone_Call {
	_c.Call.Return(run)
	return _c
}

// IncreaseOTPAttempt provides a mock function with given fields: ctx, otpID, phone
func (_m *MockIRepository) IncreaseOTPAttempt(ctx context.Context, otpID int, phone string) error {
	ret := _m.Called(ctx, otpID, phone)

	if len(ret) == 0 {
		panic("no return value specified for IncreaseOTPAttempt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, otpID, phone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRepository_IncreaseOTPAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncreaseOTPAttempt'
type MockIRepository_IncreaseOTPAttempt_Call struct {
	*mock.Call
}

// IncreaseOTPAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - otpID int
//   - phone string
func (_e *MockIRepository_Expecter) IncreaseOTPAttempt(ctx interface{}, otpID interface{}, phone interface{}) *MockIRepository_IncreaseOTPAttempt_Call {
	return &MockIRepository_IncreaseOTPAttempt_Call{Call: _e.mock.On("IncreaseOTPAttempt", ctx, otpID, phone)}
}

func (_c *MockIRepository_IncreaseOTPAttempt_Call) Run(run func(ctx context.Context, otpID int, phone string)) *MockIRepository_IncreaseOTPAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockIRepository_IncreaseOTPAttempt_Call) Return(_a0 error) *MockIRepository_IncreaseOTPAttempt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepository_IncreaseOTPAttempt_Call) RunAndReturn(run func(context.Context, int, string) error) *MockIRepository_IncreaseOTPAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOTPAsVerified provides a mock function with given fields: ctx, otpID
func (_m *MockIRepository) MarkOTPAsVerified(ctx context.Context, otpID int) error {
	ret := _m.Called(ctx, otpID)

	if len(ret) == 0 {
		panic("no return value specified for MarkOTPAsVerified")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, otpID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRepository_MarkOTPAsVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOTPAsVerified'
type MockIRepository_MarkOTPAsVerified_Call struct {
	*mock.Call
}

// MarkOTPAsVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - otpID int
func (_e *MockIRepository_Expecter) MarkOTPAsVerified(ctx interface{}, otpID interface{}) *MockIRepository_MarkOTPAsVerified_Call {
	return &MockIRepository_MarkOTPAsVerified_Call{Call: _e.mock.On("MarkOTPAsVerified", ctx, otpID)}
}

func (_c *MockIRepository_MarkOTPAsVerified_Call) Run(run func(ctx context.Context, otpID int)) *MockIRepository_MarkOTPAsVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIRepository_MarkOTPAsVerified_Call) Return(_a0 error) *MockIRepository_MarkOTPAsVerified_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepository_MarkOTPAsVerified_Call) RunAndReturn(run func(context.Context, int) error) *MockIRepository_MarkOTPAsVerified_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOTP provides a mock function with given fields: ctx, o
func (_m *MockIRepository) SaveOTP(ctx context.Context, o *models.OTP) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for SaveOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.OTP) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRepository_SaveOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOTP'
type MockIRepository_SaveOTP_Call struct {
	*mock.Call
}

// SaveOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - o *models.OTP
func (_e *MockIRepository_Expecter) SaveOTP(ctx interface{}, o interface{}) *MockIRepository_SaveOTP_Call {
	return &MockIRepository_SaveOTP_Call{Call: _e.mock.On("SaveOTP", ctx, o)}
}

func (_c *MockIRepository_SaveOTP_Call) Run(run func(ctx context.Context, o *models.OTP)) *MockIRepository_SaveOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.OTP))
	})
	return _c
}

func (_c *MockIRepository_SaveOTP_Call) Return(_a0 error) *MockIRepository_SaveOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepository_SaveOTP_Call) RunAndReturn(run func(context.Context, *models.OTP) error) *MockIRepository_SaveOTP_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBookingStatus provides a mock function with given fields: ctx, bookingID, status
func (_m *MockIRepository) UpdateBookingStatus(ctx context.Context, bookingID int, status string) error {
	ret := _m.Called(ctx, bookingID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookingStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, bookingID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRepository_UpdateBookingStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBookingStatus'
type MockIRepository_UpdateBookingStatus_Call struct {
	*mock.Call
}

// UpdateBookingStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID int
//   - status string
func (_e *MockIRepository_Expecter) UpdateBookingStatus(ctx interface{}, bookingID interface{}, status interface{}) *MockIRepository_UpdateBookingStatus_Call {
	return &MockIRepository_UpdateBookingStatus_Call{Call: _e.mock.On("UpdateBookingStatus", ctx, bookingID, status)}
}

func (_c *MockIRepository_UpdateBookingStatus_Call) Run(run func(ctx context.Context, bookingID int, status string)) *MockIRepository_UpdateBookingStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockIRepository_UpdateBookingStatus_Call) Return(_a0 error) *MockIRepository_UpdateBookingStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepository_UpdateBookingStatus_Call) RunAndReturn(run func(context.Context, int, string) error) *MockIRepository_UpdateBookingStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNeed provides a mock function with given fields: ctx, n
func (_m *MockIRepository) UpdateNeed(ctx context.Context, n *models.Need) error {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNeed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Need) error); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRepository_UpdateNeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNeed'
type MockIRepository_UpdateNeed_Call struct {
	*mock.Call
}

// UpdateNeed is a helper method to define mock.On call
//   - ctx context.Context
//   - n *models.Need
func (_e *MockIRepository_Expecter) UpdateNeed(ctx interface{}, n interface{}) *MockIRepository_UpdateNeed_Call {
	return &MockIRepository_UpdateNeed_Call{Call: _e.mock.On("UpdateNeed", ctx, n)}
}

func (_c *MockIRepository_UpdateNeed_Call) Run(run func(ctx context.Context, n *models.Need)) *MockIRepository_UpdateNeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Need))
	})
	return _c
}

func (_c *MockIRepository_UpdateNeed_Call) Return(_a0 error) *MockIRepository_UpdateNeed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepository_UpdateNeed_Call) RunAndReturn(run func(context.Context, *models.Need) error) *MockIRepository_UpdateNeed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
